apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./complete-demo.yaml
patchesStrategicMerge:
  - delete-ns.yaml  
patches:
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: replace
        path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-type
        value: external
      - op: replace
        path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-nlb-target-type
        value: ip
      - op: replace
        path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-scheme
        value: internet-facing
    target:
      version: v1
      kind: Service
      name: front-end